apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: afra-repo.jiring.local:8083/laravel-rmv:latest
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: laravel-persistent-storage
              mountPath: /var/www/html/storage
      volumes:
        - name: laravel-persistent-storage
          persistentVolumeClaim:
            claimName: laravel-pvc
