# Use the official MySQL base image
FROM mysql:latest

# Set the MySQL root password (replace <password> with your desired password)
ENV MYSQL_ROOT_PASSWORD=nePjnUwWZL4ZR3gF

# Copy the SQL script to initialize the database (replace <script.sql> with your SQL script)
#COPY <script.sql> /docker-entrypoint-initdb.d/

# Expose port 3306
EXPOSE 3306

# Start MySQL
CMD ["mysqld"]
