apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name roomview.local;
      root /var/www/html/public;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
        fastcgi_pass 172.17.0.21:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }
